### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#1]
**Describe the problem with the current version**
- Find any incorrect grammar and incorrect usage of words or if you can simply make it easier to understand. 

**Expected behavior**
- Should fix some error or make  easier to understand

**Comment by Nainish-Rai** [comment]
hey @Abhijit25Mishra I would love to contribute to this, Kindly assign me So that i can start working on it.

**Comment by Abhijit25Mishra** [comment]
Yeah, Here you go.

**Comment by Nainish-Rai** [comment]
@Abhijit25Mishra I have improved the readme and opened a pull request, Kindly check

**Comment by Victor-Okpukpan** [comment]
If this is still open, I'd like to work on it

**Comment by Abhijit25Mishra** [comment]
sure @Victor-Okpukpan .

**Comment by Victor-Okpukpan** [comment]
@Abhijit25Mishra I was not able to log back in and correct my mistakes in time before you closed and marked it as spam. I'm pleading that you unmark it, please.
