### ISSUE TITLE
Sparse Table

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#10]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Yeah sure. Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by shivam-bhadani** [comment]
Assign me this issue I can add sparse table code with good code quality

**Comment by Abhijit25Mishra** [comment]
Sure, here you go

**Comment by shivam-bhadani** [comment]
@Abhijit25Mishra  added sparse table and made pull request please merge it
