### ISSUE TITLE
Rabin-Karp 

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#11]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Yeah sure. Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

make sure to add some form of example in the description

**Comment by flow6979** [comment]
i have experience in this string algorithm. please allow me to contribute to this repository.
thank you

**Comment by Abhijit25Mishra** [comment]
@flow6979  you have already been assigned 2 issues. Finish those first then i will assign this if available.

**Comment by flow6979** [comment]
> @flow6979 you have already been assigned 2 issues. Finish those first then i will assign this if available.

finished both of them bro

**Comment by Abhijit25Mishra** [comment]
yep, assigned.
