### ISSUE TITLE
Manacher's Algorithm

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#13]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by flow6979** [comment]
hey @Abhijit25Mishra can i contribute to this repository?
thank you

**Comment by Abhijit25Mishra** [comment]
@flow6979 you have already been assigned 2 issues. Finish those first then i will assign this if available.

**Comment by Pulkitt23** [comment]
@Abhijit25Mishra can I contribute to this repository

**Comment by flow6979** [comment]
> @flow6979 you have already been assigned 2 issues. Finish those first then i will assign this if available.

brother you can assign this to me...I will do both rabin-karp and this one before morning.

**Comment by Abhijit25Mishra** [comment]
@flow6979 here u go.

**Comment by Abhijit25Mishra** [comment]
@Pulkitt23 i have assigned u a different issue. Please work on that first.
