### ISSUE TITLE
Add your Code Chef template

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#2]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.

**Comment by flow6979** [comment]
hey @Abhijit25Mishra  can you please assign this to me. i am very much excited to contribute to this repository.

**Comment by Abhijit25Mishra** [comment]
Yeah sure. Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by flow6979** [comment]
Do i need to put my snippet in general folder?

**Comment by Abhijit25Mishra** [comment]
Yes and add some sort of explaination in the same directory with in explanation folder in markdown format

**Comment by flow6979** [comment]
> Yes and add some sort of explaination in the same directory with in explanation folder in markdown format

brother, my snippet is self explanatory. i have separated function on the basis of their uses like maths,mod,string,etc.. after that i have given the functions name such that there will be no need for extra documentation to explain them.

**Comment by flow6979** [comment]
if you still found that there is some need for explanation please tell me
