### ISSUE TITLE
Time function

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#22]
This should calculate the time taken by a section of code to run.

- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Yeah sure. Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by uhditya** [comment]
Hey, please assign me this issue.

**Comment by Abhijit25Mishra** [comment]
yeah sure, go ahead.
