### ISSUE TITLE
Fenwick tree

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#24]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by NRS08** [comment]
This problem I think I can solve easily, please assign it to me

**Comment by Abhijit25Mishra** [comment]
sure go ahead.
