### ISSUE TITLE
 Get Primes upto some number n

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#25]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

**Comment by raunakkumarsingh** [comment]
ya i can solve this

**Comment by Abhijit25Mishra** [comment]
yes ok

**Comment by Aaronphilip2003** [comment]
can i get assigned this task ?
