### ISSUE TITLE
Sieve of Eratosthenes (Optimized)

### ISSUE THREAD

**Issue by Abhijit25Mishra** [Abhijit25Mishra/cp-snippets#7]
- Make sure to add a .json file. have a look at the previous contribution in this repo to get a better understanding.
- Add a markdown file explaining what the snippets does and what all is recommend to be changed.
- Add any personal recommendation if you want to.
- Explain any uncommon topics and add any resources where they can read more about it.
- Yeah sure. Be sure to maintain code quality. Use only the default CPP code to reduce any dependency.

This should be a void function that takes input of a integer and a vector. vector should be passed by reference.

**Comment by shivam-bhadani** [comment]
Hi, please assign me this issue I will work on it

**Comment by Pulkitt23** [comment]
I want to contribute on this issue. Please assign it to me

**Comment by Abhijit25Mishra** [comment]
yep, alright.
